export const DRAWER_CLOSE = 'DRAWER_CLOSE';
export const DRAWER_OPEN = 'DRAWER_OPEN';

export const ADD_DETAIL_HANDLER = 'ADD_DETAIL_HANDLER';
export const SUBMIT_DETAIL_HANDLER = 'SUBMIT_DETAIL_HANDLER';
export const ONCHANGE_HANDLER = 'ONCHANGE_HANDLER';
export const EDIT_EVENT_HANDLER = 'EDIT_EVENT_HANDLER';
export const DELETE_EVENT_HANDLER = 'DELETE_EVENT_HANDLER';